### ISSUE TITLE
Login Form 만들기

### ISSUE THREAD

**Issue by majac6** [polym-team/flowerDogTraining#1]
참고용 링크 : https://codemyui.com/signup-password-field-reaction-yeti-mascot-login-form/

간단하게 계정(이메일) 암호를 입력받고 SUBMIT 하면, 입력받은 계정과 암호를 alert 으로 표시하도록 하는 폼을 작성해야 함.
별도의 파일(ex, loginForm.html) 형태로 우선 작성할 것.

**Comment by Bekryoung** [comment]
- loginForm 브랜치를 생성했습니다.

- 예시코드의 CSS를 보면 선택자내에 또다시 선택자를 선언하는 형태를 볼 수 있습니다. 하지만 동일하게 코딩시 작동하지 않는 현상에 대해 질문드립니다.

![Uploading 스크린샷 2020-03-08 오후 10.59.19.png…]()

**Comment by selenehyun** [comment]
지나가다 들렀습니다.

## CSS 문법 레퍼런스
- http://tcpschool.com/css/css_intro_syntax

## SASS(SCSS) 문법 레퍼런스
- https://soooprmx.com/archives/7948
- http://ui-lab.co.kr/tag/scss-%EB%AC%B8%EB%B2%95/

@Bekryoung 해당 자료를 참고하시면 왜 해당 코드가 동작하지 않는지 짐작할 수 있습니다.

**Comment by Bekryoung** [comment]
@selenehyun 아예 다른 문법이었군요~ 도움이 되었습니다. 감사합니다 👍❤
