### ISSUE TITLE
Client Routing 적용하기

### ISSUE THREAD

**Issue by majac6** [polym-team/flowerDogTraining#3]
독립된 2개 이상의 페이지를 연결해야 함. 다음 경로의 샘플파일을 보고 Login 이후에 Todo List 페이지가 보이도록 해야 함.

**Comment by majac6** [comment]
샘플코드 작업후 이곳에 경로를 올릴 예정이고 그 이후에 작업을 시작할 것.

**Comment by majac6** [comment]
issue-3 브랜치에 작업해두었고
/sample/README.md 파일을 참조해 샘플 코드를 실행해볼 것.

그리고 현재 작업된 결과물을 다음 경로(route) 에 렌더링되도록 해야 함.
LoginPage : /
ToDoListPage : /Todos

**Comment by Bekryoung** [comment]
예시코드에서는 route에 hash를 적용해 hashchage이벤트를 통해 렌더를 하고 있습니다.
예시와 같이 hash를 사용해야 하나요 아니면 지시대로 해쉬를 사용하지 않은 경로로 렌더되게 해야 하나요?

**Comment by Bekryoung** [comment]
> issue-3 브랜치에 작업해두었고
> /sample/README.md 파일을 참조해 샘플 코드를 실행해볼 것.
> 
> 그리고 현재 작업된 결과물을 다음 경로(route) 에 렌더링되도록 해야 함.
> LoginPage : /
> ToDoListPage : /Todos

예시코드에서는 route에 hash를 적용해 hashchage이벤트를 통해 렌더를 하고 있습니다.
예시와 같이 hash를 사용해야 하나요 아니면 지시대로 해쉬를 사용하지 않은 경로로 렌더되게 해야 하나요?

**Comment by majac6** [comment]
해쉬를 사용해도 무방합니다!

**Comment by Bekryoung** [comment]
기존 index.html과 LoginForm.html을 html과 js파일로 분리하여 진행해도 괜찮은가요?

**Comment by majac6** [comment]
분리해도 괜찮음. 가능하다면 css 파일도 분리할 것
